# Generated by Django 4.2.25 on 2025-10-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_auther_post_author_rename_content_post_body_and_more'),
        ('blog', '0007_tag_post_tags'),
    ]

    operations = [
    ]
